[tool.poetry]
name = "ponyhw"
version = "0.1.0"
description = ""
authors = ["Adina"]

[tool.poetry.dependencies]
python = "^3.9"
pony = "^0.7.14"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
